name: Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch: # on button click
            
jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          owner: novice88
          base: main
          head: main
