name: Sync upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch upstream changes
        uses: actions/checkout@v2
        with:
          ref: upstream/main
      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories
      - name: Push changes to fork
        uses: actions/checkout@v2
        with:
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
